#!/usr/bin/env bash
# write a Bash script that configures a new Ubuntu machine nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow  'Nginx HTTP' #on port 80
sudo echo 'Hello World' > /var/www/html/index.nginx-debian.html
sudo sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo sed -i "54i add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
