#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i '$ a\ENABLED=1' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen edgarsantander \n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 3823-web-01 3.80.116.142:80 check\n\tserver 3823-web-02 34.203.212.217:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
