#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd.


while IFS= read -r line; do
      s1=$(printf '%s' "$line" | cut -d ":" -f 1)
      s2=$(printf '%s' "$line" | cut -d ":" -f 4)
      s3=$(printf '%s' "$line" | cut -d ":" -f 6)
      s4=$(printf '%s' "$line" | cut -d ":" -f 7)
      s5=$(printf '%s' "$line" | cut -d ":" -f 3)
      s6=$(printf '%s' "$line" | cut -d ":" -f 2)
      s7=$(printf '%s' "$line" | cut -d ":" -f 5)
      printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" "$s1" "$s2" "$s3" "$s4" "$s5" "$s6" "$s7"
done < /etc/passwd